services:
  - type: web
    name: rba-api
    env: node
    plan: free
    region: oregon
    rootDir: server
    buildCommand: npm install
    startCommand: npm run start
    envVars:
      - key: PORT
        value: 3001
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: CORS_ORIGIN
        sync: false
