import { History, Download, Filter } from "lucide-react";
import { useState } from "react";

export function AuditHistoryTabContent({
  auditLogs,
  currentUser,
}: {
  auditLogs: Array<{ id: number; actor: string | null; action: string; details: string | null; created_at: string }>;
  currentUser?: { name?: string; email?: string } | null;
}) {
  const [showFilters, setShowFilters] = useState(false);
  const [start, setStart] = useState<string | null>(null);
  const [end, setEnd] = useState<string | null>(null);
  const [actionFilter, setActionFilter] = useState<string | null>(null);
  const formatDateTime = (dateString: string) => {
    try {
      const normalized = dateString.includes("T") ? dateString : dateString.replace(" ", "T");
      const parsed = new Date(normalized.includes("Z") || normalized.includes("+") ? normalized : `${normalized}Z`);
      
      if (Number.isNaN(parsed.getTime())) {
        return dateString;
      }

      return new Intl.DateTimeFormat("en-PH", {
        timeZone: "Asia/Manila",
        dateStyle: "medium",
        timeStyle: "short",
      }).format(parsed);
    } catch {
      return dateString;
    }
  };

  return (
    <div className="mt-6 space-y-6">
      <div className="flex items-center justify-between gap-4 flex-wrap">
        <div>
          <p className="text-xs uppercase tracking-[0.24em] text-slate-400">System Activity</p>
          <h2 className="mt-1 text-lg font-semibold text-white">Audit History</h2>
          <p className="mt-2 text-sm text-slate-400">Complete log of all system activities and changes</p>
        </div>
        <div className="flex gap-2">
          <button onClick={() => setShowFilters((s) => !s)} className="flex items-center gap-2 rounded-xl border border-white/10 bg-slate-950/80 px-3 py-2 text-sm text-slate-200 transition hover:bg-slate-800">
            <Filter className="h-4 w-4" />
            Filter
          </button>
          <button onClick={() => {
            // prepare printable report and open print dialog
            const html = `
              <html>
                <head>
                  <title>Audit Report</title>
                  <style>
                    body { font-family: Arial, Helvetica, sans-serif; color: #111; padding: 20px; }
                    table { width: 100%; border-collapse: collapse; }
                    th, td { border: 1px solid #ddd; padding: 8px; }
                    th { background: #f3f4f6; }
                    footer { position: fixed; bottom: 20px; left: 0; right: 0; text-align: center; font-size: 12px; color: rgba(0,0,0,0.5); }
                    .watermark { position: fixed; bottom: 40px; right: 20px; font-size: 10px; color: rgba(0,0,0,0.2); }
                  </style>
                </head>
                <body>
                  <h2>Audit Report</h2>
                  <p>Generated by: ${currentUser?.name ?? currentUser?.email ?? 'Unknown'}</p>
                  <table>
                    <thead><tr><th>Action</th><th>Actor</th><th>Details</th><th>Timestamp</th></tr></thead>
                    <tbody>
                      ${auditLogs.map(log => `<tr><td>${log.action}</td><td>${log.actor || 'System'}</td><td>${(log.details||'').replace(/</g,'&lt;')}</td><td>${log.created_at}</td></tr>`).join('')}
                    </tbody>
                  </table>
                  <footer>Report generated by ${currentUser?.name ?? currentUser?.email ?? 'Unknown'}</footer>
                  <div class="watermark">Generated by ${currentUser?.name ?? currentUser?.email ?? 'Unknown'}</div>
                </body>
              </html>
            `;
            const w = window.open('', '_blank');
            if (!w) return;
            w.document.write(html);
            w.document.close();
            w.focus();
            setTimeout(() => w.print(), 500);
          }} className="flex items-center gap-2 rounded-xl border border-white/10 bg-slate-950/80 px-3 py-2 text-sm text-slate-200 transition hover:bg-slate-800">
            <Download className="h-4 w-4" />
            Export
          </button>
        </div>
      </div>

      {showFilters && (
        <div className="rounded-2xl border border-white/10 bg-slate-950/80 p-4">
          <div className="grid gap-2 md:grid-cols-3">
            <input type="datetime-local" onChange={(e) => setStart(e.target.value || null)} className="rounded-xl border border-white/10 bg-slate-900 px-3 py-2 text-sm text-white" />
            <input type="datetime-local" onChange={(e) => setEnd(e.target.value || null)} className="rounded-xl border border-white/10 bg-slate-900 px-3 py-2 text-sm text-white" />
            <input placeholder="Action contains..." onChange={(e) => setActionFilter(e.target.value || null)} className="rounded-xl border border-white/10 bg-slate-900 px-3 py-2 text-sm text-white" />
          </div>
          <div className="mt-3">
            <button onClick={() => {
              const params = new URLSearchParams();
              if (start) params.set('start', start);
              if (end) params.set('end', end);
              if (actionFilter) params.set('action', actionFilter);
              const url = `/api/admin/audit-logs?${params.toString()}`;
              fetch(url).then(r => r.json()).then(d => {
                if (d.success) {
                  // reload page with filtered logs by replacing table contents
                  window.location.reload();
                }
              });
            }} className="rounded-xl bg-blue-600 px-3 py-2 text-sm text-white">Apply filters</button>
          </div>
        </div>
      )}

      <div className="rounded-3xl border border-white/10 bg-slate-900/80 overflow-hidden">
        <div className="overflow-x-auto">
          <table className="w-full">
            <thead>
              <tr className="border-b border-white/10">
                <th className="px-6 py-3 text-left text-xs font-semibold uppercase tracking-wider text-slate-400">Action</th>
                <th className="px-6 py-3 text-left text-xs font-semibold uppercase tracking-wider text-slate-400">Actor</th>
                <th className="px-6 py-3 text-left text-xs font-semibold uppercase tracking-wider text-slate-400">Details</th>
                <th className="px-6 py-3 text-left text-xs font-semibold uppercase tracking-wider text-slate-400">Timestamp</th>
              </tr>
            </thead>
            <tbody>
              {auditLogs.length === 0 ? (
                <tr>
                  <td colSpan={4} className="px-6 py-8 text-center text-sm text-slate-400">
                    <div className="flex flex-col items-center justify-center gap-3">
                      <History className="h-8 w-8 text-slate-600" />
                      <span>No audit history available</span>
                    </div>
                  </td>
                </tr>
              ) : (
                auditLogs.map((log) => (
                  <tr key={log.id} className="border-b border-white/5 hover:bg-white/2 transition">
                    <td className="px-6 py-4">
                      <div className="flex items-center gap-2">
                        <div className="h-2 w-2 rounded-full bg-blue-400" />
                        <span className="text-sm font-medium text-white">{log.action}</span>
                      </div>
                    </td>
                    <td className="px-6 py-4 text-sm text-slate-300">{log.actor || "System"}</td>
                    <td className="px-6 py-4 text-sm text-slate-400">{log.details || "—"}</td>
                    <td className="px-6 py-4 text-sm text-slate-400">{formatDateTime(log.created_at)}</td>
                  </tr>
                ))
              )}
            </tbody>
          </table>
        </div>
      </div>

      {auditLogs.length > 0 && (
        <div className="rounded-2xl border border-white/10 bg-slate-950/80 p-4">
          <p className="text-sm text-slate-400">
            Showing <span className="font-semibold text-white">{auditLogs.length}</span> activities
          </p>
        </div>
      )}
    </div>
  );
}
